/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import tools.Util;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;

/**
 *
 * @author felip
 */
public class JDlgProduto extends javax.swing.JDialog {

   private MaskFormatter mascaraCpf;
    private MaskFormatter mascaraData;

    /**
     * /**
     * Creates new form JDlgFuncionario
     */
    public JDlgProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setTitle("Cadastro Funcionario");
        setLocationRelativeTo(null);
        initComponents();

        Util.habilitar(false, jTxtCodigo, jTxtNome, jTxtEstoque, jTxtDesc, jTxtEstoque, jLblNome, jLblCodigo, jLblDescricao, jLblEstoque, jBtnConfirmar, jBtnCancelar);
        try {
            mascaraCpf = new MaskFormatter("###.###.###-##");
        } catch (ParseException ex) {
            Logger.getLogger(JDlgUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
//    jFmtCpf.setFormatterFactory(new DefaultFormatterFactory(mascaraCpf));
        try {
            mascaraData = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(JDlgUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
//    jFmtDataNasc.setFormatterFactory(new DefaultFormatterFactory(mascaraData));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblCodigo = new javax.swing.JLabel();
        jLblEstoque = new javax.swing.JLabel();
        jLblNome = new javax.swing.JLabel();
        jLblDescricao = new javax.swing.JLabel();
        jTxtCodigo = new javax.swing.JTextField();
        jTxtNome = new javax.swing.JTextField();
        jTxtEstoque = new javax.swing.JTextField();
        jTxtDesc = new javax.swing.JTextField();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblCodigo.setText("Codigo");

        jLblEstoque.setText("Estoque");

        jLblNome.setText("Nome do Produto");

        jLblDescricao.setText("Descrição");

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar_1.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExcluir))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLblCodigo)
                        .addComponent(jLblNome)
                        .addComponent(jTxtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                        .addComponent(jTxtNome)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLblDescricao)
                        .addComponent(jLblEstoque)
                        .addComponent(jTxtEstoque)
                        .addComponent(jTxtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnPesquisar)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCodigo)
                    .addComponent(jLblEstoque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNome)
                    .addComponent(jLblDescricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnPesquisar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        Util.habilitar(true, jTxtCodigo, jTxtNome, jTxtEstoque, jTxtDesc, jTxtEstoque, jLblNome, jLblCodigo, jLblDescricao, jLblEstoque, jBtnConfirmar, jBtnCancelar);
        Util.habilitar(false,jBtnAlterar,jBtnIncluir,jBtnExcluir,jBtnPesquisar);
        Util.limpar(jTxtCodigo, jTxtNome, jTxtEstoque, jTxtDesc, jTxtEstoque);
        jTxtCodigo.grabFocus();
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        JOptionPane.showMessageDialog(null, "Alterado com sucesso...");
        Util.habilitar(true, jTxtCodigo, jTxtNome, jTxtEstoque, jTxtDesc, jTxtEstoque, jLblNome, jLblCodigo, jLblDescricao, jLblEstoque, jBtnConfirmar, jBtnCancelar);
        Util.habilitar(false,jBtnAlterar,jBtnIncluir,jBtnExcluir,jBtnPesquisar);
        Util.limpar(jTxtCodigo, jTxtNome, jTxtEstoque, jTxtDesc, jTxtEstoque);
        habilitar(true);
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        JOptionPane.showMessageDialog(null, "Exclusão");
       // int resp = JOptionPane.showConfirmDialog(null, "Confirma Exclusão", "Deletar Registro", JOptionPane.YES_NO_OPTION);
      //  if (resp == JOptionPane.YES_OPTION){
      //      FMJ_produto produto = new FMJ_produto();
     //  int cod = Integer.valueOf(jTxtCodigo.getText());
      // produto.setFMJ_idProduto(cod);
      // produto.setFMJ_NomeProduto(jTxtNome.getText());
      // produto.setFMJ_descProduto(jTxtDesc.getText());
      // produto.setFMJ_estoqueProduto(jTxtEstoque.getText());
      // ProdutoDao produtoDAO = new ProdutoDao();
      // produtoDAO.delete(produto);
        //    JOptionPane.showMessageDialog(null, "Exclusão Ok!");
    }//GEN-LAST:event_jBtnExcluirActionPerformed
   // }
    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
     //  FMJ_produto produto = new FMJ_produto();
     //  int cod = Integer.valueOf(jTxtCodigo.getText());
     //  produto.setFMJ_idProduto(cod);
     //  produto.setFMJ_NomeProduto(jTxtNome.getText());
    //   produto.setFMJ_descProduto(jTxtDesc.getText());
    //   produto.setFMJ_estoqueProduto(jTxtEstoque.getText());
     //  
     //  ProdutoDao produtoDAO = new ProdutoDao();
    //   produtoDAO.insert(produto);
    Util.habilitar(false, jTxtCodigo, jTxtNome, jTxtEstoque, jTxtDesc, jTxtEstoque, jLblNome, jLblCodigo, jLblDescricao, jLblEstoque, jBtnConfirmar, jBtnCancelar);
        Util.habilitar(true,jBtnAlterar,jBtnIncluir,jBtnExcluir,jBtnPesquisar);
        Util.limpar(jTxtCodigo, jTxtNome, jTxtEstoque, jTxtDesc, jTxtEstoque);;
               
        
      //  JOptionPane.showMessageDialog(null, "Salvo!");
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
         Util.habilitar(true, jTxtCodigo, jTxtNome, jTxtEstoque, jTxtDesc, jTxtEstoque, jLblNome, jLblCodigo, jLblDescricao, jLblEstoque, jBtnConfirmar, jBtnCancelar);
        Util.habilitar(false,jBtnAlterar,jBtnIncluir,jBtnExcluir,jBtnPesquisar);
        Util.limpar(jTxtCodigo, jTxtNome, jTxtEstoque, jTxtDesc, jTxtEstoque);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        //String resp = JOptionPane.showInputDialog(null, "Entre com o Código de Usuário");
      //  if (resp == null ){
       //     JOptionPane.showMessageDialog(null, "codigo em branco");
       // } else {
       ///     ProdutoDao produtoDAO = new ProdutoDao();
        //    int cod = Integer.valueOf(resp);
        //    FMJ_produto produto = (FMJ_produto) produtoDAO.list(cod);
            
      //  resp = String.valueOf(produto.getFMJ_idProduto());
      // jTxtCodigo.setText(resp);
       // jTxtNome.setText(produto.getFMJ_NomeProduto());
      //  jTxtDesc.setText(produto.getFMJ_descProduto());
       // jTxtEstoque.setText(produto.getFMJ_estoqueProduto());
     
      //  }
      JDlgProdutoPesq jDlgProdutoPesq = new JDlgProdutoPesq();
        jDlgProdutoPesq.setVisible(true);
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    public void limpar(){
        jTxtNome.setText("");
         jTxtCodigo.setText("");
         jTxtDesc.setText("");
         jTxtEstoque.setText("");
    }
    
    
     private void habilitar(boolean valor){
         jTxtNome.setEnabled(valor);
         jTxtCodigo.setEnabled(valor);
         jTxtDesc.setEnabled(valor);
         jTxtEstoque.setEnabled(valor);
         
        jBtnIncluir.setEnabled(!valor);
        jBtnAlterar.setEnabled(!valor);
        jBtnExcluir.setEnabled(!valor);
        jBtnPesquisar.setEnabled(!valor);
         
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgProduto dialog = new JDlgProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JLabel jLblCodigo;
    private javax.swing.JLabel jLblDescricao;
    private javax.swing.JLabel jLblEstoque;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtDesc;
    private javax.swing.JTextField jTxtEstoque;
    private javax.swing.JTextField jTxtNome;
    // End of variables declaration//GEN-END:variables
}
