package bean;
// Generated 16/12/2024 18:10:32 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FmjCompra generated by hbm2java
 */
@Entity
@Table(name="fmj_compra"
    ,catalog="db_vinicius_carvalho"
)
public class FmjCompra  implements java.io.Serializable {


     private int fmjIdCompra;
     private FmjFornecedor fmjFornecedor;
     private Date fmjDataCompra;
     private String fmjFormadePagamento;
     private BigDecimal fmjValorTotal;
     private String fmjObservacoes;
     private String fmjNomeProduto;
     private String fmjStatusdeCompra;
     private String fmjFornecedor_1;
     private String fmjAtivo;
     private Set fmjCompraProdutos = new HashSet(0);

    public FmjCompra() {
    }

	
    public FmjCompra(int fmjIdCompra, FmjFornecedor fmjFornecedor, String fmjFormadePagamento, BigDecimal fmjValorTotal, String fmjObservacoes, String fmjNomeProduto, String fmjStatusdeCompra, String fmjFornecedor_1, String fmjAtivo) {
        this.fmjIdCompra = fmjIdCompra;
        this.fmjFornecedor = fmjFornecedor;
        this.fmjFormadePagamento = fmjFormadePagamento;
        this.fmjValorTotal = fmjValorTotal;
        this.fmjObservacoes = fmjObservacoes;
        this.fmjNomeProduto = fmjNomeProduto;
        this.fmjStatusdeCompra = fmjStatusdeCompra;
        this.fmjFornecedor_1 = fmjFornecedor_1;
        this.fmjAtivo = fmjAtivo;
    }
    public FmjCompra(int fmjIdCompra, FmjFornecedor fmjFornecedor, Date fmjDataCompra, String fmjFormadePagamento, BigDecimal fmjValorTotal, String fmjObservacoes, String fmjNomeProduto, String fmjStatusdeCompra, String fmjFornecedor_1, String fmjAtivo, Set fmjCompraProdutos) {
       this.fmjIdCompra = fmjIdCompra;
       this.fmjFornecedor = fmjFornecedor;
       this.fmjDataCompra = fmjDataCompra;
       this.fmjFormadePagamento = fmjFormadePagamento;
       this.fmjValorTotal = fmjValorTotal;
       this.fmjObservacoes = fmjObservacoes;
       this.fmjNomeProduto = fmjNomeProduto;
       this.fmjStatusdeCompra = fmjStatusdeCompra;
       this.fmjFornecedor_1 = fmjFornecedor_1;
       this.fmjAtivo = fmjAtivo;
       this.fmjCompraProdutos = fmjCompraProdutos;
    }
   
     @Id 

    
    @Column(name="FMJ_idCompra", unique=true, nullable=false)
    public int getFmjIdCompra() {
        return this.fmjIdCompra;
    }
    
    public void setFmjIdCompra(int fmjIdCompra) {
        this.fmjIdCompra = fmjIdCompra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FMJ_fk_fornecedor", nullable=false)
    public FmjFornecedor getFmjFornecedor() {
        return this.fmjFornecedor;
    }
    
    public void setFmjFornecedor(FmjFornecedor fmjFornecedor) {
        this.fmjFornecedor = fmjFornecedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FMJ_dataCompra", length=10)
    public Date getFmjDataCompra() {
        return this.fmjDataCompra;
    }
    
    public void setFmjDataCompra(Date fmjDataCompra) {
        this.fmjDataCompra = fmjDataCompra;
    }

    
    @Column(name="FMJ_formadePagamento", nullable=false, length=100)
    public String getFmjFormadePagamento() {
        return this.fmjFormadePagamento;
    }
    
    public void setFmjFormadePagamento(String fmjFormadePagamento) {
        this.fmjFormadePagamento = fmjFormadePagamento;
    }

    
    @Column(name="FMJ_valorTotal", nullable=false, precision=5)
    public BigDecimal getFmjValorTotal() {
        return this.fmjValorTotal;
    }
    
    public void setFmjValorTotal(BigDecimal fmjValorTotal) {
        this.fmjValorTotal = fmjValorTotal;
    }

    
    @Column(name="FMJ_observacoes", nullable=false, length=65535)
    public String getFmjObservacoes() {
        return this.fmjObservacoes;
    }
    
    public void setFmjObservacoes(String fmjObservacoes) {
        this.fmjObservacoes = fmjObservacoes;
    }

    
    @Column(name="FMJ_nomeProduto", nullable=false, length=40)
    public String getFmjNomeProduto() {
        return this.fmjNomeProduto;
    }
    
    public void setFmjNomeProduto(String fmjNomeProduto) {
        this.fmjNomeProduto = fmjNomeProduto;
    }

    
    @Column(name="FMJ_StatusdeCompra", nullable=false, length=120)
    public String getFmjStatusdeCompra() {
        return this.fmjStatusdeCompra;
    }
    
    public void setFmjStatusdeCompra(String fmjStatusdeCompra) {
        this.fmjStatusdeCompra = fmjStatusdeCompra;
    }

    
    @Column(name="FMJ_fornecedor", nullable=false, length=100)
    public String getFmjFornecedor_1() {
        return this.fmjFornecedor_1;
    }
    
    public void setFmjFornecedor_1(String fmjFornecedor_1) {
        this.fmjFornecedor_1 = fmjFornecedor_1;
    }

    
    @Column(name="FMJ_ativo", nullable=false, length=1)
    public String getFmjAtivo() {
        return this.fmjAtivo;
    }
    
    public void setFmjAtivo(String fmjAtivo) {
        this.fmjAtivo = fmjAtivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fmjCompra")
    public Set getFmjCompraProdutos() {
        return this.fmjCompraProdutos;
    }
    
    public void setFmjCompraProdutos(Set fmjCompraProdutos) {
        this.fmjCompraProdutos = fmjCompraProdutos;
    }




}


