package bean;
// Generated 16/12/2024 18:10:32 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FmjCompraProduto generated by hbm2java
 */
@Entity
@Table(name="fmj_compra_produto"
    ,catalog="db_vinicius_carvalho"
)
public class FmjCompraProduto  implements java.io.Serializable {


     private String fmjIdCompraProduto;
     private FmjCompra fmjCompra;
     private FmjProduto fmjProduto;
     private double fmjPrecoUnitario;
     private String fmjQuantidade;

    public FmjCompraProduto() {
    }

    public FmjCompraProduto(String fmjIdCompraProduto, FmjCompra fmjCompra, FmjProduto fmjProduto, double fmjPrecoUnitario, String fmjQuantidade) {
       this.fmjIdCompraProduto = fmjIdCompraProduto;
       this.fmjCompra = fmjCompra;
       this.fmjProduto = fmjProduto;
       this.fmjPrecoUnitario = fmjPrecoUnitario;
       this.fmjQuantidade = fmjQuantidade;
    }
   
     @Id 

    
    @Column(name="FMJ_idCompraProduto", unique=true, nullable=false, length=45)
    public String getFmjIdCompraProduto() {
        return this.fmjIdCompraProduto;
    }
    
    public void setFmjIdCompraProduto(String fmjIdCompraProduto) {
        this.fmjIdCompraProduto = fmjIdCompraProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FMJ_fk_Compra", nullable=false)
    public FmjCompra getFmjCompra() {
        return this.fmjCompra;
    }
    
    public void setFmjCompra(FmjCompra fmjCompra) {
        this.fmjCompra = fmjCompra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FMJ_fk_Produto", nullable=false)
    public FmjProduto getFmjProduto() {
        return this.fmjProduto;
    }
    
    public void setFmjProduto(FmjProduto fmjProduto) {
        this.fmjProduto = fmjProduto;
    }

    
    @Column(name="FMJ_precoUnitario", nullable=false, precision=22, scale=0)
    public double getFmjPrecoUnitario() {
        return this.fmjPrecoUnitario;
    }
    
    public void setFmjPrecoUnitario(double fmjPrecoUnitario) {
        this.fmjPrecoUnitario = fmjPrecoUnitario;
    }

    
    @Column(name="FMJ_quantidade", nullable=false, length=45)
    public String getFmjQuantidade() {
        return this.fmjQuantidade;
    }
    
    public void setFmjQuantidade(String fmjQuantidade) {
        this.fmjQuantidade = fmjQuantidade;
    }




}


