package bean;
// Generated 16/12/2024 18:10:32 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FmjDestaque generated by hbm2java
 */
@Entity
@Table(name="fmj_destaque"
    ,catalog="db_vinicius_carvalho"
)
public class FmjDestaque  implements java.io.Serializable {


     private int fmjIdDestaque;
     private String fmjNomeDestaque;
     private String fmjDescDestaque;
     private Date fmjDataInicioDestaque;
     private Date fmjDataTerminoDestaque;
     private String fmjAtivo;
     private String fmjOrdem;
     private String fmjTipoDestaque;

    public FmjDestaque() {
    }

	
    public FmjDestaque(int fmjIdDestaque, String fmjNomeDestaque, String fmjDescDestaque, String fmjAtivo, String fmjOrdem, String fmjTipoDestaque) {
        this.fmjIdDestaque = fmjIdDestaque;
        this.fmjNomeDestaque = fmjNomeDestaque;
        this.fmjDescDestaque = fmjDescDestaque;
        this.fmjAtivo = fmjAtivo;
        this.fmjOrdem = fmjOrdem;
        this.fmjTipoDestaque = fmjTipoDestaque;
    }
    public FmjDestaque(int fmjIdDestaque, String fmjNomeDestaque, String fmjDescDestaque, Date fmjDataInicioDestaque, Date fmjDataTerminoDestaque, String fmjAtivo, String fmjOrdem, String fmjTipoDestaque) {
       this.fmjIdDestaque = fmjIdDestaque;
       this.fmjNomeDestaque = fmjNomeDestaque;
       this.fmjDescDestaque = fmjDescDestaque;
       this.fmjDataInicioDestaque = fmjDataInicioDestaque;
       this.fmjDataTerminoDestaque = fmjDataTerminoDestaque;
       this.fmjAtivo = fmjAtivo;
       this.fmjOrdem = fmjOrdem;
       this.fmjTipoDestaque = fmjTipoDestaque;
    }
   
     @Id 

    
    @Column(name="FMJ_idDestaque", unique=true, nullable=false)
    public int getFmjIdDestaque() {
        return this.fmjIdDestaque;
    }
    
    public void setFmjIdDestaque(int fmjIdDestaque) {
        this.fmjIdDestaque = fmjIdDestaque;
    }

    
    @Column(name="FMJ_NomeDestaque", nullable=false, length=100)
    public String getFmjNomeDestaque() {
        return this.fmjNomeDestaque;
    }
    
    public void setFmjNomeDestaque(String fmjNomeDestaque) {
        this.fmjNomeDestaque = fmjNomeDestaque;
    }

    
    @Column(name="FMJ_descDestaque", nullable=false, length=500)
    public String getFmjDescDestaque() {
        return this.fmjDescDestaque;
    }
    
    public void setFmjDescDestaque(String fmjDescDestaque) {
        this.fmjDescDestaque = fmjDescDestaque;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FMJ_dataInicioDestaque", length=10)
    public Date getFmjDataInicioDestaque() {
        return this.fmjDataInicioDestaque;
    }
    
    public void setFmjDataInicioDestaque(Date fmjDataInicioDestaque) {
        this.fmjDataInicioDestaque = fmjDataInicioDestaque;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FMJ_dataTerminoDestaque", length=10)
    public Date getFmjDataTerminoDestaque() {
        return this.fmjDataTerminoDestaque;
    }
    
    public void setFmjDataTerminoDestaque(Date fmjDataTerminoDestaque) {
        this.fmjDataTerminoDestaque = fmjDataTerminoDestaque;
    }

    
    @Column(name="FMJ_ativo", nullable=false, length=1)
    public String getFmjAtivo() {
        return this.fmjAtivo;
    }
    
    public void setFmjAtivo(String fmjAtivo) {
        this.fmjAtivo = fmjAtivo;
    }

    
    @Column(name="fmj_ordem", nullable=false, length=45)
    public String getFmjOrdem() {
        return this.fmjOrdem;
    }
    
    public void setFmjOrdem(String fmjOrdem) {
        this.fmjOrdem = fmjOrdem;
    }

    
    @Column(name="fmj_tipoDestaque", nullable=false, length=45)
    public String getFmjTipoDestaque() {
        return this.fmjTipoDestaque;
    }
    
    public void setFmjTipoDestaque(String fmjTipoDestaque) {
        this.fmjTipoDestaque = fmjTipoDestaque;
    }




}


