package bean;
// Generated 16/12/2024 18:10:32 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FmjFuncionarios generated by hbm2java
 */
@Entity
@Table(name="fmj_funcionarios"
    ,catalog="db_vinicius_carvalho"
)
public class FmjFuncionarios  implements java.io.Serializable {


     private int fmjIdFuncionario;
     private String fmjNomeFuncionario;
     private String fmjEmailFuncionario;
     private String fmjTelefoneFuncionario;
     private String fmjRegiaoDeAtuacaoFuncionario;
     private String fmjHistoricoDeVendasFuncionario;
     private String fmjComissoesFuncionario;
     private String fmjDesempenhoFuncionario;
     private String fmjAtivo;

    public FmjFuncionarios() {
    }

	
    public FmjFuncionarios(int fmjIdFuncionario, String fmjNomeFuncionario, String fmjEmailFuncionario, String fmjTelefoneFuncionario, String fmjRegiaoDeAtuacaoFuncionario) {
        this.fmjIdFuncionario = fmjIdFuncionario;
        this.fmjNomeFuncionario = fmjNomeFuncionario;
        this.fmjEmailFuncionario = fmjEmailFuncionario;
        this.fmjTelefoneFuncionario = fmjTelefoneFuncionario;
        this.fmjRegiaoDeAtuacaoFuncionario = fmjRegiaoDeAtuacaoFuncionario;
    }
    public FmjFuncionarios(int fmjIdFuncionario, String fmjNomeFuncionario, String fmjEmailFuncionario, String fmjTelefoneFuncionario, String fmjRegiaoDeAtuacaoFuncionario, String fmjHistoricoDeVendasFuncionario, String fmjComissoesFuncionario, String fmjDesempenhoFuncionario, String fmjAtivo) {
       this.fmjIdFuncionario = fmjIdFuncionario;
       this.fmjNomeFuncionario = fmjNomeFuncionario;
       this.fmjEmailFuncionario = fmjEmailFuncionario;
       this.fmjTelefoneFuncionario = fmjTelefoneFuncionario;
       this.fmjRegiaoDeAtuacaoFuncionario = fmjRegiaoDeAtuacaoFuncionario;
       this.fmjHistoricoDeVendasFuncionario = fmjHistoricoDeVendasFuncionario;
       this.fmjComissoesFuncionario = fmjComissoesFuncionario;
       this.fmjDesempenhoFuncionario = fmjDesempenhoFuncionario;
       this.fmjAtivo = fmjAtivo;
    }
   
     @Id 

    
    @Column(name="FMJ_idFuncionario", unique=true, nullable=false)
    public int getFmjIdFuncionario() {
        return this.fmjIdFuncionario;
    }
    
    public void setFmjIdFuncionario(int fmjIdFuncionario) {
        this.fmjIdFuncionario = fmjIdFuncionario;
    }

    
    @Column(name="FMJ_nomeFuncionario", nullable=false, length=45)
    public String getFmjNomeFuncionario() {
        return this.fmjNomeFuncionario;
    }
    
    public void setFmjNomeFuncionario(String fmjNomeFuncionario) {
        this.fmjNomeFuncionario = fmjNomeFuncionario;
    }

    
    @Column(name="FMJ_emailFuncionario", nullable=false, length=50)
    public String getFmjEmailFuncionario() {
        return this.fmjEmailFuncionario;
    }
    
    public void setFmjEmailFuncionario(String fmjEmailFuncionario) {
        this.fmjEmailFuncionario = fmjEmailFuncionario;
    }

    
    @Column(name="FMJ_telefoneFuncionario", nullable=false, length=14)
    public String getFmjTelefoneFuncionario() {
        return this.fmjTelefoneFuncionario;
    }
    
    public void setFmjTelefoneFuncionario(String fmjTelefoneFuncionario) {
        this.fmjTelefoneFuncionario = fmjTelefoneFuncionario;
    }

    
    @Column(name="FMJ_regiaoDeAtuacaoFuncionario", nullable=false, length=45)
    public String getFmjRegiaoDeAtuacaoFuncionario() {
        return this.fmjRegiaoDeAtuacaoFuncionario;
    }
    
    public void setFmjRegiaoDeAtuacaoFuncionario(String fmjRegiaoDeAtuacaoFuncionario) {
        this.fmjRegiaoDeAtuacaoFuncionario = fmjRegiaoDeAtuacaoFuncionario;
    }

    
    @Column(name="FMJ_historicoDeVendasFuncionario", length=30)
    public String getFmjHistoricoDeVendasFuncionario() {
        return this.fmjHistoricoDeVendasFuncionario;
    }
    
    public void setFmjHistoricoDeVendasFuncionario(String fmjHistoricoDeVendasFuncionario) {
        this.fmjHistoricoDeVendasFuncionario = fmjHistoricoDeVendasFuncionario;
    }

    
    @Column(name="FMJ_comissoesFuncionario", length=30)
    public String getFmjComissoesFuncionario() {
        return this.fmjComissoesFuncionario;
    }
    
    public void setFmjComissoesFuncionario(String fmjComissoesFuncionario) {
        this.fmjComissoesFuncionario = fmjComissoesFuncionario;
    }

    
    @Column(name="FMJ_desempenhoFuncionario", length=10)
    public String getFmjDesempenhoFuncionario() {
        return this.fmjDesempenhoFuncionario;
    }
    
    public void setFmjDesempenhoFuncionario(String fmjDesempenhoFuncionario) {
        this.fmjDesempenhoFuncionario = fmjDesempenhoFuncionario;
    }

    
    @Column(name="FMJ_ativo", length=1)
    public String getFmjAtivo() {
        return this.fmjAtivo;
    }
    
    public void setFmjAtivo(String fmjAtivo) {
        this.fmjAtivo = fmjAtivo;
    }




}


