package bean;
// Generated 16/12/2024 18:10:32 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FmjFornecedor generated by hbm2java
 */
@Entity
@Table(name="fmj_fornecedor"
    ,catalog="db_vinicius_carvalho"
)
public class FmjFornecedor  implements java.io.Serializable {


     private int fmjIdFornecedor;
     private String fmjNomeEmpresa;
     private String fmjContatoEmpresa;
     private String fmjEnderecoEmpresa;
     private String fmjTelefoneEmpresa;
     private String fmjEmailEmpresa;
     private String fmjTipoFornecedor;
     private String fmjNumIdentificacaoFiscal;
     private String fmjHistoricoTransacoes;
     private Date fmjPrazoEntrega;
     private BigDecimal fmjCustoEntrega;
     private String fmjCategoriaProduto;
     private Date fmjDataCadastro;
     private BigDecimal fmjValorTotal;
     private BigDecimal fmjSaldoPendente;
     private String fmjAtivo;
     private Set fmjCompras = new HashSet(0);

    public FmjFornecedor() {
    }

	
    public FmjFornecedor(int fmjIdFornecedor, String fmjNomeEmpresa, String fmjContatoEmpresa, String fmjEnderecoEmpresa, String fmjTelefoneEmpresa, String fmjEmailEmpresa) {
        this.fmjIdFornecedor = fmjIdFornecedor;
        this.fmjNomeEmpresa = fmjNomeEmpresa;
        this.fmjContatoEmpresa = fmjContatoEmpresa;
        this.fmjEnderecoEmpresa = fmjEnderecoEmpresa;
        this.fmjTelefoneEmpresa = fmjTelefoneEmpresa;
        this.fmjEmailEmpresa = fmjEmailEmpresa;
    }
    public FmjFornecedor(int fmjIdFornecedor, String fmjNomeEmpresa, String fmjContatoEmpresa, String fmjEnderecoEmpresa, String fmjTelefoneEmpresa, String fmjEmailEmpresa, String fmjTipoFornecedor, String fmjNumIdentificacaoFiscal, String fmjHistoricoTransacoes, Date fmjPrazoEntrega, BigDecimal fmjCustoEntrega, String fmjCategoriaProduto, Date fmjDataCadastro, BigDecimal fmjValorTotal, BigDecimal fmjSaldoPendente, String fmjAtivo, Set fmjCompras) {
       this.fmjIdFornecedor = fmjIdFornecedor;
       this.fmjNomeEmpresa = fmjNomeEmpresa;
       this.fmjContatoEmpresa = fmjContatoEmpresa;
       this.fmjEnderecoEmpresa = fmjEnderecoEmpresa;
       this.fmjTelefoneEmpresa = fmjTelefoneEmpresa;
       this.fmjEmailEmpresa = fmjEmailEmpresa;
       this.fmjTipoFornecedor = fmjTipoFornecedor;
       this.fmjNumIdentificacaoFiscal = fmjNumIdentificacaoFiscal;
       this.fmjHistoricoTransacoes = fmjHistoricoTransacoes;
       this.fmjPrazoEntrega = fmjPrazoEntrega;
       this.fmjCustoEntrega = fmjCustoEntrega;
       this.fmjCategoriaProduto = fmjCategoriaProduto;
       this.fmjDataCadastro = fmjDataCadastro;
       this.fmjValorTotal = fmjValorTotal;
       this.fmjSaldoPendente = fmjSaldoPendente;
       this.fmjAtivo = fmjAtivo;
       this.fmjCompras = fmjCompras;
    }
   
     @Id 

    
    @Column(name="FMJ_IdFornecedor", unique=true, nullable=false)
    public int getFmjIdFornecedor() {
        return this.fmjIdFornecedor;
    }
    
    public void setFmjIdFornecedor(int fmjIdFornecedor) {
        this.fmjIdFornecedor = fmjIdFornecedor;
    }

    
    @Column(name="FMJ_nomeEmpresa", nullable=false, length=60)
    public String getFmjNomeEmpresa() {
        return this.fmjNomeEmpresa;
    }
    
    public void setFmjNomeEmpresa(String fmjNomeEmpresa) {
        this.fmjNomeEmpresa = fmjNomeEmpresa;
    }

    
    @Column(name="FMJ_contatoEmpresa", nullable=false, length=60)
    public String getFmjContatoEmpresa() {
        return this.fmjContatoEmpresa;
    }
    
    public void setFmjContatoEmpresa(String fmjContatoEmpresa) {
        this.fmjContatoEmpresa = fmjContatoEmpresa;
    }

    
    @Column(name="FMJ_enderecoEmpresa", nullable=false, length=45)
    public String getFmjEnderecoEmpresa() {
        return this.fmjEnderecoEmpresa;
    }
    
    public void setFmjEnderecoEmpresa(String fmjEnderecoEmpresa) {
        this.fmjEnderecoEmpresa = fmjEnderecoEmpresa;
    }

    
    @Column(name="FMJ_telefoneEmpresa", nullable=false, length=14)
    public String getFmjTelefoneEmpresa() {
        return this.fmjTelefoneEmpresa;
    }
    
    public void setFmjTelefoneEmpresa(String fmjTelefoneEmpresa) {
        this.fmjTelefoneEmpresa = fmjTelefoneEmpresa;
    }

    
    @Column(name="FMJ_emailEmpresa", nullable=false, length=45)
    public String getFmjEmailEmpresa() {
        return this.fmjEmailEmpresa;
    }
    
    public void setFmjEmailEmpresa(String fmjEmailEmpresa) {
        this.fmjEmailEmpresa = fmjEmailEmpresa;
    }

    
    @Column(name="FMJ_tipoFornecedor", length=30)
    public String getFmjTipoFornecedor() {
        return this.fmjTipoFornecedor;
    }
    
    public void setFmjTipoFornecedor(String fmjTipoFornecedor) {
        this.fmjTipoFornecedor = fmjTipoFornecedor;
    }

    
    @Column(name="FMJ_numIdentificacaoFiscal", length=30)
    public String getFmjNumIdentificacaoFiscal() {
        return this.fmjNumIdentificacaoFiscal;
    }
    
    public void setFmjNumIdentificacaoFiscal(String fmjNumIdentificacaoFiscal) {
        this.fmjNumIdentificacaoFiscal = fmjNumIdentificacaoFiscal;
    }

    
    @Column(name="FMJ_historicoTransacoes", length=60)
    public String getFmjHistoricoTransacoes() {
        return this.fmjHistoricoTransacoes;
    }
    
    public void setFmjHistoricoTransacoes(String fmjHistoricoTransacoes) {
        this.fmjHistoricoTransacoes = fmjHistoricoTransacoes;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FMJ_prazoEntrega", length=10)
    public Date getFmjPrazoEntrega() {
        return this.fmjPrazoEntrega;
    }
    
    public void setFmjPrazoEntrega(Date fmjPrazoEntrega) {
        this.fmjPrazoEntrega = fmjPrazoEntrega;
    }

    
    @Column(name="FMJ_custoEntrega", precision=4)
    public BigDecimal getFmjCustoEntrega() {
        return this.fmjCustoEntrega;
    }
    
    public void setFmjCustoEntrega(BigDecimal fmjCustoEntrega) {
        this.fmjCustoEntrega = fmjCustoEntrega;
    }

    
    @Column(name="FMJ_categoriaProduto", length=45)
    public String getFmjCategoriaProduto() {
        return this.fmjCategoriaProduto;
    }
    
    public void setFmjCategoriaProduto(String fmjCategoriaProduto) {
        this.fmjCategoriaProduto = fmjCategoriaProduto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FMJ_dataCadastro", length=10)
    public Date getFmjDataCadastro() {
        return this.fmjDataCadastro;
    }
    
    public void setFmjDataCadastro(Date fmjDataCadastro) {
        this.fmjDataCadastro = fmjDataCadastro;
    }

    
    @Column(name="FMJ_valorTotal", precision=5)
    public BigDecimal getFmjValorTotal() {
        return this.fmjValorTotal;
    }
    
    public void setFmjValorTotal(BigDecimal fmjValorTotal) {
        this.fmjValorTotal = fmjValorTotal;
    }

    
    @Column(name="FMJ_saldoPendente", precision=5)
    public BigDecimal getFmjSaldoPendente() {
        return this.fmjSaldoPendente;
    }
    
    public void setFmjSaldoPendente(BigDecimal fmjSaldoPendente) {
        this.fmjSaldoPendente = fmjSaldoPendente;
    }

    
    @Column(name="FMJ_ativo", length=1)
    public String getFmjAtivo() {
        return this.fmjAtivo;
    }
    
    public void setFmjAtivo(String fmjAtivo) {
        this.fmjAtivo = fmjAtivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fmjFornecedor")
    public Set getFmjCompras() {
        return this.fmjCompras;
    }
    
    public void setFmjCompras(Set fmjCompras) {
        this.fmjCompras = fmjCompras;
    }




}


