package bean;
// Generated 16/12/2024 18:10:32 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FmjProduto generated by hbm2java
 */
@Entity
@Table(name="fmj_produto"
    ,catalog="db_vinicius_carvalho"
)
public class FmjProduto  implements java.io.Serializable {


     private int fmjIdProduto;
     private String fmjNomeProduto;
     private String fmjDescProduto;
     private BigDecimal fmjPrecoProduto;
     private String fmjEstoqueProduto;
     private String fmjCategoriaProduto;
     private Date fmjDataCadastro;
     private String fmjAtivo;
     private Set fmjCompraProdutos = new HashSet(0);
     private Set vscVendaProdutos = new HashSet(0);

    public FmjProduto() {
    }

	
    public FmjProduto(int fmjIdProduto, String fmjNomeProduto, String fmjDescProduto, String fmjEstoqueProduto) {
        this.fmjIdProduto = fmjIdProduto;
        this.fmjNomeProduto = fmjNomeProduto;
        this.fmjDescProduto = fmjDescProduto;
        this.fmjEstoqueProduto = fmjEstoqueProduto;
    }
    public FmjProduto(int fmjIdProduto, String fmjNomeProduto, String fmjDescProduto, BigDecimal fmjPrecoProduto, String fmjEstoqueProduto, String fmjCategoriaProduto, Date fmjDataCadastro, String fmjAtivo, Set fmjCompraProdutos, Set vscVendaProdutos) {
       this.fmjIdProduto = fmjIdProduto;
       this.fmjNomeProduto = fmjNomeProduto;
       this.fmjDescProduto = fmjDescProduto;
       this.fmjPrecoProduto = fmjPrecoProduto;
       this.fmjEstoqueProduto = fmjEstoqueProduto;
       this.fmjCategoriaProduto = fmjCategoriaProduto;
       this.fmjDataCadastro = fmjDataCadastro;
       this.fmjAtivo = fmjAtivo;
       this.fmjCompraProdutos = fmjCompraProdutos;
       this.vscVendaProdutos = vscVendaProdutos;
    }
   
     @Id 

    
    @Column(name="FMJ_idProduto", unique=true, nullable=false)
    public int getFmjIdProduto() {
        return this.fmjIdProduto;
    }
    
    public void setFmjIdProduto(int fmjIdProduto) {
        this.fmjIdProduto = fmjIdProduto;
    }

    
    @Column(name="FMJ_NomeProduto", nullable=false, length=120)
    public String getFmjNomeProduto() {
        return this.fmjNomeProduto;
    }
    
    public void setFmjNomeProduto(String fmjNomeProduto) {
        this.fmjNomeProduto = fmjNomeProduto;
    }

    
    @Column(name="FMJ_descProduto", nullable=false, length=500)
    public String getFmjDescProduto() {
        return this.fmjDescProduto;
    }
    
    public void setFmjDescProduto(String fmjDescProduto) {
        this.fmjDescProduto = fmjDescProduto;
    }

    
    @Column(name="FMJ_precoProduto", precision=4)
    public BigDecimal getFmjPrecoProduto() {
        return this.fmjPrecoProduto;
    }
    
    public void setFmjPrecoProduto(BigDecimal fmjPrecoProduto) {
        this.fmjPrecoProduto = fmjPrecoProduto;
    }

    
    @Column(name="FMJ_estoqueProduto", nullable=false, length=20)
    public String getFmjEstoqueProduto() {
        return this.fmjEstoqueProduto;
    }
    
    public void setFmjEstoqueProduto(String fmjEstoqueProduto) {
        this.fmjEstoqueProduto = fmjEstoqueProduto;
    }

    
    @Column(name="FMJ_categoriaProduto", length=20)
    public String getFmjCategoriaProduto() {
        return this.fmjCategoriaProduto;
    }
    
    public void setFmjCategoriaProduto(String fmjCategoriaProduto) {
        this.fmjCategoriaProduto = fmjCategoriaProduto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FMJ_dataCadastro", length=10)
    public Date getFmjDataCadastro() {
        return this.fmjDataCadastro;
    }
    
    public void setFmjDataCadastro(Date fmjDataCadastro) {
        this.fmjDataCadastro = fmjDataCadastro;
    }

    
    @Column(name="FMJ_ativo", length=1)
    public String getFmjAtivo() {
        return this.fmjAtivo;
    }
    
    public void setFmjAtivo(String fmjAtivo) {
        this.fmjAtivo = fmjAtivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fmjProduto")
    public Set getFmjCompraProdutos() {
        return this.fmjCompraProdutos;
    }
    
    public void setFmjCompraProdutos(Set fmjCompraProdutos) {
        this.fmjCompraProdutos = fmjCompraProdutos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fmjProduto")
    public Set getVscVendaProdutos() {
        return this.vscVendaProdutos;
    }
    
    public void setVscVendaProdutos(Set vscVendaProdutos) {
        this.vscVendaProdutos = vscVendaProdutos;
    }




}


