package bean;
// Generated 16/12/2024 18:10:32 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VscCliente generated by hbm2java
 */
@Entity
@Table(name="vsc_cliente"
    ,catalog="db_vinicius_carvalho"
)
public class VscCliente  implements java.io.Serializable {


     private int vscIdCliente;
     private String vscNome;
     private String vscSobrenome;
     private String vscEndereco;
     private String vscNumTelefone;
     private String vscEnderecoEmail;
     private Date vscDataNasc;
     private String vscGenero;
     private String vscRg;
     private String vscGenerosFavoritos;
     private String vscPreferenciaDeComunicacao;
     private String vscHistoricoCompras;
     private Date vscDataCadastro;
     private Date vscUltimaDataCompra;
     private String vscAtivo;
     private Set vscVendas = new HashSet(0);

    public VscCliente() {
    }

	
    public VscCliente(int vscIdCliente, String vscNome, String vscSobrenome, String vscEndereco, String vscNumTelefone, String vscEnderecoEmail, String vscGenero, String vscRg, String vscGenerosFavoritos, String vscPreferenciaDeComunicacao) {
        this.vscIdCliente = vscIdCliente;
        this.vscNome = vscNome;
        this.vscSobrenome = vscSobrenome;
        this.vscEndereco = vscEndereco;
        this.vscNumTelefone = vscNumTelefone;
        this.vscEnderecoEmail = vscEnderecoEmail;
        this.vscGenero = vscGenero;
        this.vscRg = vscRg;
        this.vscGenerosFavoritos = vscGenerosFavoritos;
        this.vscPreferenciaDeComunicacao = vscPreferenciaDeComunicacao;
    }
    public VscCliente(int vscIdCliente, String vscNome, String vscSobrenome, String vscEndereco, String vscNumTelefone, String vscEnderecoEmail, Date vscDataNasc, String vscGenero, String vscRg, String vscGenerosFavoritos, String vscPreferenciaDeComunicacao, String vscHistoricoCompras, Date vscDataCadastro, Date vscUltimaDataCompra, String vscAtivo, Set vscVendas) {
       this.vscIdCliente = vscIdCliente;
       this.vscNome = vscNome;
       this.vscSobrenome = vscSobrenome;
       this.vscEndereco = vscEndereco;
       this.vscNumTelefone = vscNumTelefone;
       this.vscEnderecoEmail = vscEnderecoEmail;
       this.vscDataNasc = vscDataNasc;
       this.vscGenero = vscGenero;
       this.vscRg = vscRg;
       this.vscGenerosFavoritos = vscGenerosFavoritos;
       this.vscPreferenciaDeComunicacao = vscPreferenciaDeComunicacao;
       this.vscHistoricoCompras = vscHistoricoCompras;
       this.vscDataCadastro = vscDataCadastro;
       this.vscUltimaDataCompra = vscUltimaDataCompra;
       this.vscAtivo = vscAtivo;
       this.vscVendas = vscVendas;
    }
   
     @Id 

    
    @Column(name="VSC_id_cliente", unique=true, nullable=false)
    public int getVscIdCliente() {
        return this.vscIdCliente;
    }
    
    public void setVscIdCliente(int vscIdCliente) {
        this.vscIdCliente = vscIdCliente;
    }

    
    @Column(name="VSC_nome", nullable=false, length=20)
    public String getVscNome() {
        return this.vscNome;
    }
    
    public void setVscNome(String vscNome) {
        this.vscNome = vscNome;
    }

    
    @Column(name="VSC_sobrenome", nullable=false, length=50)
    public String getVscSobrenome() {
        return this.vscSobrenome;
    }
    
    public void setVscSobrenome(String vscSobrenome) {
        this.vscSobrenome = vscSobrenome;
    }

    
    @Column(name="VSC_endereco", nullable=false, length=80)
    public String getVscEndereco() {
        return this.vscEndereco;
    }
    
    public void setVscEndereco(String vscEndereco) {
        this.vscEndereco = vscEndereco;
    }

    
    @Column(name="VSC_numTelefone", nullable=false, length=14)
    public String getVscNumTelefone() {
        return this.vscNumTelefone;
    }
    
    public void setVscNumTelefone(String vscNumTelefone) {
        this.vscNumTelefone = vscNumTelefone;
    }

    
    @Column(name="VSC_enderecoEmail", nullable=false, length=50)
    public String getVscEnderecoEmail() {
        return this.vscEnderecoEmail;
    }
    
    public void setVscEnderecoEmail(String vscEnderecoEmail) {
        this.vscEnderecoEmail = vscEnderecoEmail;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VSC_dataNasc", length=10)
    public Date getVscDataNasc() {
        return this.vscDataNasc;
    }
    
    public void setVscDataNasc(Date vscDataNasc) {
        this.vscDataNasc = vscDataNasc;
    }

    
    @Column(name="VSC_genero", nullable=false, length=12)
    public String getVscGenero() {
        return this.vscGenero;
    }
    
    public void setVscGenero(String vscGenero) {
        this.vscGenero = vscGenero;
    }

    
    @Column(name="VSC_Rg", nullable=false, length=8)
    public String getVscRg() {
        return this.vscRg;
    }
    
    public void setVscRg(String vscRg) {
        this.vscRg = vscRg;
    }

    
    @Column(name="VSC_generosFavoritos", nullable=false, length=50)
    public String getVscGenerosFavoritos() {
        return this.vscGenerosFavoritos;
    }
    
    public void setVscGenerosFavoritos(String vscGenerosFavoritos) {
        this.vscGenerosFavoritos = vscGenerosFavoritos;
    }

    
    @Column(name="VSC_preferencia_de_Comunicacao", nullable=false, length=2)
    public String getVscPreferenciaDeComunicacao() {
        return this.vscPreferenciaDeComunicacao;
    }
    
    public void setVscPreferenciaDeComunicacao(String vscPreferenciaDeComunicacao) {
        this.vscPreferenciaDeComunicacao = vscPreferenciaDeComunicacao;
    }

    
    @Column(name="VSC_historicoCompras", length=50)
    public String getVscHistoricoCompras() {
        return this.vscHistoricoCompras;
    }
    
    public void setVscHistoricoCompras(String vscHistoricoCompras) {
        this.vscHistoricoCompras = vscHistoricoCompras;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VSC_dataCadastro", length=10)
    public Date getVscDataCadastro() {
        return this.vscDataCadastro;
    }
    
    public void setVscDataCadastro(Date vscDataCadastro) {
        this.vscDataCadastro = vscDataCadastro;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VSC_ultimaDataCompra", length=10)
    public Date getVscUltimaDataCompra() {
        return this.vscUltimaDataCompra;
    }
    
    public void setVscUltimaDataCompra(Date vscUltimaDataCompra) {
        this.vscUltimaDataCompra = vscUltimaDataCompra;
    }

    
    @Column(name="VSC_ativo", length=1)
    public String getVscAtivo() {
        return this.vscAtivo;
    }
    
    public void setVscAtivo(String vscAtivo) {
        this.vscAtivo = vscAtivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vscCliente")
    public Set getVscVendas() {
        return this.vscVendas;
    }
    
    public void setVscVendas(Set vscVendas) {
        this.vscVendas = vscVendas;
    }




}


