package bean;
// Generated 16/12/2024 18:10:32 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VscUsuario generated by hbm2java
 */
@Entity
@Table(name="vsc_usuario"
    ,catalog="db_vinicius_carvalho"
)
public class VscUsuario  implements java.io.Serializable {


     private int vscIdUsuarios;
     private String vscNomeUsuario;
     private String vscApelidoUsuario;
     private String vscCpfUsuario;
     private Date vscDataNascUsuario;
     private String vscSenhaUsuario;
     private int vscNivelUsuario;
     private String vscAtivo;

    public VscUsuario() {
    }

	
    public VscUsuario(int vscIdUsuarios, String vscNomeUsuario, String vscApelidoUsuario, String vscCpfUsuario, String vscSenhaUsuario, int vscNivelUsuario) {
        this.vscIdUsuarios = vscIdUsuarios;
        this.vscNomeUsuario = vscNomeUsuario;
        this.vscApelidoUsuario = vscApelidoUsuario;
        this.vscCpfUsuario = vscCpfUsuario;
        this.vscSenhaUsuario = vscSenhaUsuario;
        this.vscNivelUsuario = vscNivelUsuario;
    }
    public VscUsuario(int vscIdUsuarios, String vscNomeUsuario, String vscApelidoUsuario, String vscCpfUsuario, Date vscDataNascUsuario, String vscSenhaUsuario, int vscNivelUsuario, String vscAtivo) {
       this.vscIdUsuarios = vscIdUsuarios;
       this.vscNomeUsuario = vscNomeUsuario;
       this.vscApelidoUsuario = vscApelidoUsuario;
       this.vscCpfUsuario = vscCpfUsuario;
       this.vscDataNascUsuario = vscDataNascUsuario;
       this.vscSenhaUsuario = vscSenhaUsuario;
       this.vscNivelUsuario = vscNivelUsuario;
       this.vscAtivo = vscAtivo;
    }
   
     @Id 

    
    @Column(name="VSC_idUsuarios", unique=true, nullable=false)
    public int getVscIdUsuarios() {
        return this.vscIdUsuarios;
    }
    
    public void setVscIdUsuarios(int vscIdUsuarios) {
        this.vscIdUsuarios = vscIdUsuarios;
    }

    
    @Column(name="VSC_nomeUsuario", nullable=false, length=50)
    public String getVscNomeUsuario() {
        return this.vscNomeUsuario;
    }
    
    public void setVscNomeUsuario(String vscNomeUsuario) {
        this.vscNomeUsuario = vscNomeUsuario;
    }

    
    @Column(name="VSC_apelidoUsuario", nullable=false, length=25)
    public String getVscApelidoUsuario() {
        return this.vscApelidoUsuario;
    }
    
    public void setVscApelidoUsuario(String vscApelidoUsuario) {
        this.vscApelidoUsuario = vscApelidoUsuario;
    }

    
    @Column(name="VSC_cpfUsuario", nullable=false, length=14)
    public String getVscCpfUsuario() {
        return this.vscCpfUsuario;
    }
    
    public void setVscCpfUsuario(String vscCpfUsuario) {
        this.vscCpfUsuario = vscCpfUsuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VSC_dataNascUsuario", length=10)
    public Date getVscDataNascUsuario() {
        return this.vscDataNascUsuario;
    }
    
    public void setVscDataNascUsuario(Date vscDataNascUsuario) {
        this.vscDataNascUsuario = vscDataNascUsuario;
    }

    
    @Column(name="VSC_senhaUsuario", nullable=false, length=30)
    public String getVscSenhaUsuario() {
        return this.vscSenhaUsuario;
    }
    
    public void setVscSenhaUsuario(String vscSenhaUsuario) {
        this.vscSenhaUsuario = vscSenhaUsuario;
    }

    
    @Column(name="VSC_nivelUsuario", nullable=false)
    public int getVscNivelUsuario() {
        return this.vscNivelUsuario;
    }
    
    public void setVscNivelUsuario(int vscNivelUsuario) {
        this.vscNivelUsuario = vscNivelUsuario;
    }

    
    @Column(name="VSC_ativo", length=10)
    public String getVscAtivo() {
        return this.vscAtivo;
    }
    
    public void setVscAtivo(String vscAtivo) {
        this.vscAtivo = vscAtivo;
    }




}


