package bean;
// Generated 16/12/2024 18:10:32 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VscVenda generated by hbm2java
 */
@Entity
@Table(name="vsc_venda"
    ,catalog="db_vinicius_carvalho"
)
public class VscVenda  implements java.io.Serializable {


     private int vscIdvenda;
     private VscCliente vscCliente;
     private Date vscDataVenda;
     private String vscStatusdeVenda;
     private BigDecimal vscValorTotal;
     private String vscFormasdePagamento;
     private String vscObservacoes;
     private String vscNomeProduto;
     private String vscAtivo;
     private Set vscVendaProdutos = new HashSet(0);

    public VscVenda() {
    }

	
    public VscVenda(int vscIdvenda, VscCliente vscCliente, String vscStatusdeVenda, BigDecimal vscValorTotal, String vscFormasdePagamento, String vscObservacoes, String vscNomeProduto, String vscAtivo) {
        this.vscIdvenda = vscIdvenda;
        this.vscCliente = vscCliente;
        this.vscStatusdeVenda = vscStatusdeVenda;
        this.vscValorTotal = vscValorTotal;
        this.vscFormasdePagamento = vscFormasdePagamento;
        this.vscObservacoes = vscObservacoes;
        this.vscNomeProduto = vscNomeProduto;
        this.vscAtivo = vscAtivo;
    }
    public VscVenda(int vscIdvenda, VscCliente vscCliente, Date vscDataVenda, String vscStatusdeVenda, BigDecimal vscValorTotal, String vscFormasdePagamento, String vscObservacoes, String vscNomeProduto, String vscAtivo, Set vscVendaProdutos) {
       this.vscIdvenda = vscIdvenda;
       this.vscCliente = vscCliente;
       this.vscDataVenda = vscDataVenda;
       this.vscStatusdeVenda = vscStatusdeVenda;
       this.vscValorTotal = vscValorTotal;
       this.vscFormasdePagamento = vscFormasdePagamento;
       this.vscObservacoes = vscObservacoes;
       this.vscNomeProduto = vscNomeProduto;
       this.vscAtivo = vscAtivo;
       this.vscVendaProdutos = vscVendaProdutos;
    }
   
     @Id 

    
    @Column(name="VSC_idvenda", unique=true, nullable=false)
    public int getVscIdvenda() {
        return this.vscIdvenda;
    }
    
    public void setVscIdvenda(int vscIdvenda) {
        this.vscIdvenda = vscIdvenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="VSC_fk_cliente", nullable=false)
    public VscCliente getVscCliente() {
        return this.vscCliente;
    }
    
    public void setVscCliente(VscCliente vscCliente) {
        this.vscCliente = vscCliente;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VSC_dataVenda", length=10)
    public Date getVscDataVenda() {
        return this.vscDataVenda;
    }
    
    public void setVscDataVenda(Date vscDataVenda) {
        this.vscDataVenda = vscDataVenda;
    }

    
    @Column(name="VSC_StatusdeVenda", nullable=false, length=100)
    public String getVscStatusdeVenda() {
        return this.vscStatusdeVenda;
    }
    
    public void setVscStatusdeVenda(String vscStatusdeVenda) {
        this.vscStatusdeVenda = vscStatusdeVenda;
    }

    
    @Column(name="VSC_valorTotal", nullable=false, precision=5)
    public BigDecimal getVscValorTotal() {
        return this.vscValorTotal;
    }
    
    public void setVscValorTotal(BigDecimal vscValorTotal) {
        this.vscValorTotal = vscValorTotal;
    }

    
    @Column(name="VSC_FormasdePagamento", nullable=false, length=100)
    public String getVscFormasdePagamento() {
        return this.vscFormasdePagamento;
    }
    
    public void setVscFormasdePagamento(String vscFormasdePagamento) {
        this.vscFormasdePagamento = vscFormasdePagamento;
    }

    
    @Column(name="VSC_observacoes", nullable=false, length=65535)
    public String getVscObservacoes() {
        return this.vscObservacoes;
    }
    
    public void setVscObservacoes(String vscObservacoes) {
        this.vscObservacoes = vscObservacoes;
    }

    
    @Column(name="VSC_nomeProduto", nullable=false, length=50)
    public String getVscNomeProduto() {
        return this.vscNomeProduto;
    }
    
    public void setVscNomeProduto(String vscNomeProduto) {
        this.vscNomeProduto = vscNomeProduto;
    }

    
    @Column(name="VSC_ativo", nullable=false, length=1)
    public String getVscAtivo() {
        return this.vscAtivo;
    }
    
    public void setVscAtivo(String vscAtivo) {
        this.vscAtivo = vscAtivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vscVenda")
    public Set getVscVendaProdutos() {
        return this.vscVendaProdutos;
    }
    
    public void setVscVendaProdutos(Set vscVendaProdutos) {
        this.vscVendaProdutos = vscVendaProdutos;
    }




}


