package bean;
// Generated 16/12/2024 18:10:32 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VscVendaProduto generated by hbm2java
 */
@Entity
@Table(name="vsc_venda_produto"
    ,catalog="db_vinicius_carvalho"
)
public class VscVendaProduto  implements java.io.Serializable {


     private int vscIdvendaProduto;
     private FmjProduto fmjProduto;
     private VscVenda vscVenda;
     private double vscPrecoUnitario;
     private String vscQuantidade;

    public VscVendaProduto() {
    }

    public VscVendaProduto(int vscIdvendaProduto, FmjProduto fmjProduto, VscVenda vscVenda, double vscPrecoUnitario, String vscQuantidade) {
       this.vscIdvendaProduto = vscIdvendaProduto;
       this.fmjProduto = fmjProduto;
       this.vscVenda = vscVenda;
       this.vscPrecoUnitario = vscPrecoUnitario;
       this.vscQuantidade = vscQuantidade;
    }
   
     @Id 

    
    @Column(name="vsc_idvendaProduto", unique=true, nullable=false)
    public int getVscIdvendaProduto() {
        return this.vscIdvendaProduto;
    }
    
    public void setVscIdvendaProduto(int vscIdvendaProduto) {
        this.vscIdvendaProduto = vscIdvendaProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FMJ_fk_Produto", nullable=false)
    public FmjProduto getFmjProduto() {
        return this.fmjProduto;
    }
    
    public void setFmjProduto(FmjProduto fmjProduto) {
        this.fmjProduto = fmjProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="VSC_fk_venda", nullable=false)
    public VscVenda getVscVenda() {
        return this.vscVenda;
    }
    
    public void setVscVenda(VscVenda vscVenda) {
        this.vscVenda = vscVenda;
    }

    
    @Column(name="VSC_precoUnitario", nullable=false, precision=22, scale=0)
    public double getVscPrecoUnitario() {
        return this.vscPrecoUnitario;
    }
    
    public void setVscPrecoUnitario(double vscPrecoUnitario) {
        this.vscPrecoUnitario = vscPrecoUnitario;
    }

    
    @Column(name="VSC_quantidade", nullable=false, length=45)
    public String getVscQuantidade() {
        return this.vscQuantidade;
    }
    
    public void setVscQuantidade(String vscQuantidade) {
        this.vscQuantidade = vscQuantidade;
    }




}


